// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyievckqvughkqjppnma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aWV2Y2txdnVnaGtxanBwbm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Njk3NDYsImV4cCI6MjA2OTM0NTc0Nn0.OuPGxRQDgno7m4HpxcpWez-1ZrDpFG1xZVb0L376_Ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});